---

  - name: Install supporting tools
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - wget

  - name: Create directory
    file:
      path: "{{ home_dir }}/kind"
      state: directory
      mode: '0755'

  - name: Download kind file
    get_url:
      url: https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
      dest: "{{ home_dir }}/kind/kind"
      mode: '0755'

  - name: Change permission
    file:
      path: "{{ home_dir }}/kind/kind"
      mode: +x
